### ISSUE TITLE
Missing extension key

### ISSUE THREAD

**Issue by conpassione** [in2code-de/osm#1]
composer complains about a missing extension key:
The TYPO3 extension package "in2code/osm", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

Somthing like this has to be included in composer.json:
"extra": { "typo3/cms": { "extension-key": "osm" } }

**Comment by conpassione** [comment]
Uups, sorry there is allready a ext key in the actual composer json... sorry!

**Comment by einpraegsam** [comment]
No prob, I will close this issue
