### ISSUE TITLE
Missing "type" in TCA of field "['tt_address']['description']['config']".

### ISSUE THREAD

**Issue by linawolf** [in2code-de/osm#11]
As soon as I install in2code/osm (4.0.0) I get the following error in both frontend and backend:

Missing "type" in TCA of field "['tt_address']['description']['config']".

this seems to be due to the fact, that the Extension tries to extend the TCA of tt_address without checking weather it is installed at all.

**Comment by helmut-winkelbach** [comment]
the same here with 4.0.1
#1482394401 UnexpectedValueException
Missing "type" in TCA of field "['tt_address']['description']['config']".

**Comment by linawolf** [comment]
@helmut-winkelbach you have to install tt_address or modify the TCA yourself

**Comment by helmut-winkelbach** [comment]
Hi Lina, thanks for your swift answer.
Maybe you did modify the TCA by yourself?
If yes, would you like to share it?

**Comment by linawolf** [comment]
I just installed tt_address as  I needed it anyway...

**Comment by einpraegsam** [comment]
I just published 4.0.2 that should prevent this error. Thx for reporting.
