### ISSUE TITLE
In Typo 12 error if tt_address is not installed

### ISSUE THREAD

**Issue by fennecgit** [in2code-de/osm#13]
After installing osm without tt_address I had an error.
To fix this error I would suggest to change the content of following file osm/Configuration/TCA/Overrides/tt_address.php to this:

**<?php
if (!defined('TYPO3')) {
    die('Access denied.');
}
if (\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('tt_address')) {
$GLOBALS['TCA']['tt_address']['columns']['description']['config']['enableRichtext'] = false;
}**

I would like to thank you in advance for the implementation and wish you continued successful programming.

**Comment by einpraegsam** [comment]
Duplicated to https://github.com/in2code-de/osm/issues/11
