### ISSUE TITLE
How can I set the center of the Map

### ISSUE THREAD

**Issue by linawolf** [in2code-de/osm#3]
The center seems to be set at 0, 0 Which is somewhere beyond Africa

**Comment by einpraegsam** [comment]
Oh, it's some time ago when I played with this extension. But I think the map is automatically centered when you add one or more POI (addresses)? Are you using the ext without address?

**Comment by linawolf** [comment]
I am using the extension with adresses directly entered, no tt_adress. And centering does not seem to work.

I am on TYPO3 11

**Comment by linawolf** [comment]
Well, I tried. But found out the extension is still using OpenLayers 2.0 which has been deprecated in a while. See https://github.com/openlayers/ol2 

Documentation on OpenLayers 2.0 was very hard to find and I didn't get the center repaired. So I fear I have to check out other extensions.

**Comment by einpraegsam** [comment]
I just took a quick look into the existing JS, I think https://github.com/in2code-de/osm/blob/514b579625f43735f8e743272455f1ae11704c13/Resources/Public/JavaScript/Local/Osm.js#L89 is the point were the default coordinates should be calculated.
If version 2 of openlayers is outdated, we should rewrite the JS any time in the futre.
