### ISSUE TITLE
TYPO3.CMS.deprecations": with $extensionName ("In2code.osm")

### ISSUE THREAD

**Issue by helmut-winkelbach** [in2code-de/osm#5]
I get this error very frequently.
TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Calling method TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin with argument $extensionName ("In2code.osm") containing the vendor name ("In2code") is deprecated and will stop working in TYPO3 11.0

**Comment by einpraegsam** [comment]
Thx, I just released 3.1.0 that should prevent those warnings in future
