### ISSUE TITLE
TYPO3 V12 compatibility :: Available via EAP

### ISSUE THREAD

**Issue by mschwemer** [in2code-de/osm#6]
There will be an EXT:osm version, which is compatible with TYPO3 core V12.

If you need early access to this version, please head over to https://www.in2code.de/agentur/typo3-extensions/early-access-programm/ and support our work.

**Comment by einpraegsam** [comment]
Correction: OSM for TYPO3 12 is already available via EAP

**Comment by mschwemer** [comment]
EXT:osm is now publicly available here and via TER.
